### ISSUE TITLE
Support for several profiles

### ISSUE THREAD

**Issue by squalou** [buty4649/ulauncher-firefox-bookmarks#2]
Hi,

I'm using sevaral profiles in firefox. My main profile is *not* the default one.
As a result : my bookmarks are not all available.

It would be great to add a parameter in the extension to support one, (or why not : several / all available) profiles.

**Comment by buty4649** [comment]
Hi, @squalou 
Thank you for using it.
I have upgraded the version to allow multiple profiles.

![image](https://user-images.githubusercontent.com/1275643/107979580-2badfb80-7002-11eb-886f-3d9088b226e0.png)

Please give it a try!

**Comment by squalou** [comment]
Works great,
thank you !
